[package]
name = "jed"
version = "0.1.0"
edition = "2021"
authors = ["WindProphet <lihanyuan1996@gmail.com>"]

[dependencies]
clap = "3.0.0-beta.5"
serde_json = {version = "1.0", features = ["preserve_order"]}
